### ISSUE TITLE
Setting Suggestions

### ISSUE THREAD

**Issue by Navnedia** [chromezoneeths/ethsbell-extension#1]
You should add the ability to set your default schedule view for the extension. **For example:** If someone wants their extension to always show the timeline view when they open it

**Comment by Navnedia** [comment]
I know you have a lot to do with not a lot of time, but if you find the time, or continue working on this later, I have another good suggestion. 

I don't know if this is already the case, but it would be cool if the extension could follow the same custom theming and names as the config options on the website if that would be possible. If that's possible you could just have a link in the extensions settings page that takes you to the website config page. Alternatively, you could have the ability to change those things on your extension settings page. I just think it would be nice if they could have their custom names and theme there and not just on the site, because, after all, most kids are probably going to be using the extension more.

**Comment by Navnedia** [comment]
I know you have a lot to do with not a lot of time, but if you find the time, or continue working on this later, I have another good suggestion.

I don't know if this is already the case, but it would be cool if the extension could follow the same custom theming and names as the config options on the website if that would be possible. If that's possible you could just have a link in the extensions settings page that takes you to the website config page. Alternatively, you could have the ability to change those things on your extension settings page. I just think it would be nice if they could have their custom names and theme there and not just on the site, because, after all, most kids are probably going to be using the extension more.

**Comment by asportnoy** [comment]
Added in [v2.2.0](https://github.com/chromezoneeths/ethsbell-extension/releases/tag/v2.2.0)
